# DB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/walk_holic?characterEncoding=UTF-8
    username: root
    password: tlsshrla2@

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop